[package]
name = "cartopars"
version = "0.1.0"
authors = ["Sjoerd <sjoerd-github@linuxonly.nl>"]
edition = "2018"

[dependencies]
pest = "2.1.2"
pest_derive = "2.1.0"
yaml-rust = "0.4"
stopwatch = "0.0.7"
